apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 3  # İstediğiniz sayıda replica (pod) belirleyebilirsiniz.
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app-container
        image: web-app-image:1.0
        ports:
        - containerPort: 8080